matinv:
	gcc -Wall ./src/matrix_inverse.c -o ./src/matinv

kmeans: 
	gcc -Wall ./src/kmeans.c -o ./src/kmeans

clean:
	rm -f *.o a.out ./src/kmeans ./src/matinv ./../computed_results/kmeans-results.txt
